hibernate:
    dialect:
        mssql: org.hibernate.dialect.SQLServer2012Dialect
        mysql: org.hibernate.dialect.MySQL8Dialect
        oracle: org.hibernate.dialect.Oracle10gDialect
management:
    endpoints:
        web:
            exposure:
                include: '*'
server:
    port: 8080
    servlet:
        encoding:
            charset: UTF-8
            enabled: true
            force: true
        session:
            tracking-modes: COOKIE
        context-path: /code
spring:
    application:
        name: code
    aop:
        auto: false
        proxy-target-class: true
    autoconfigure:
        exclude:
            - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    cloud:
        nacos:
            server-addr: https://test.youshengyun.com:443
            username: nacos
            password: ${NACOS_PASSWORD:111111}
            config:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
            discovery:
                enabled: false
                group: DEFAULT_GROUP
                namespace: test
    config:
        import:
            - optional:nacos:code.yml
            #- optional:nacos:test01.yml?group=group_02
            #- optional:nacos:test02.yml?group=group_03&refreshEnabled=false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
            y9-public:
                driver-class-name: com.mysql.cj.jdbc.Driver
                url: jdbc:mysql://localhost:3306/y9_public?serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&rewriteBatchedStatements=true&useCompression=true&useSSL=false&allowPublicKeyRetrieval=true
                username: root
                password: 111111
                initialSize: 1
                maxActive: 20
                maxPoolPreparedStatementPerConnectionSize: 100
                maxWait: 60000
                minEvictableIdleTimeMillis: 300000
                minIdle: 1
                poolPreparedStatements: true
                testOnBorrow: false
                testOnReturn: false
                testWhileIdle: true
                timeBetweenEvictionRunsMillis: 60000
                useGlobalDataSourceStat: true
                validationQuery: SELECT 1 FROM DUAL
    jpa:
        hibernate:
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        open-in-view: false
        properties:
            hibernate:
                cache:
                    use_query_cache: false
                    use_second_level_cache: false
                dialect: org.hibernate.dialect.MySQL8Dialect
                hbm2ddl:
                    auto: update
                jdbc:
                    batch_size: 100
                show_sql: false
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            auto-commit-interval: 1000
            enable-auto-commit: true
            group-id: y9Code-server
    main:
        allow-bean-definition-overriding: true
    mvc:
        view:
            prefix: /WEB-INF/jsp/
            suffix: .jsp
    redis:
        database: 9
        host: 192.168.3.31
        lettuce:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1
                min-idle: 0
            shutdown-timeout: 100ms
        password: 111111
        port: 6379
        ssl: false
        timeout: 10000
y9:
    systemName: code
    internalIp: 192.168.x.x,10.0.x.x,172.20.x.x
    app:
        code:
            allAreaRole: 区领导查看角色
            defaultContactGroupName: 默认分组
            defaultContactName: 未命名
            systemName: code
    service:
        org:
            directUrl: http://localhost:7055/org
    common:
        cacheEnabled: true
        kafkaEnabled: true
        orgBaseUrl: http://localhost:7055/platform
        y9DigitalBaseUrl: http://localhost:7055/y9DigitalBase
        userOnlineBaseUrl: http://localhost:7055/userOnline
        logBaseUrl: http://localhost:7055/log
    feature:
        file:
            rest:
                fileManagerUrl: http://localhost:7055/fileManager
            base64FileName: false
            encryptionFileContent: false
            ftp:
                host: localhost
                port: 21
                username: admin
                password: 111111
                blockWhenExhausted: true
                bufferSize: 10240
                connectTimeOut: 50000
                controlEncoding: UTF-8
                dataTimeout: 1200000
                fileType: 2
                maxIdle: 10
                maxTotal: 50
                minIdle: 2
                maxWaitMillis: 5400000
                testOnBorrow: true
                testOnCreate: true
                testOnReturn: true
                testWhileIdle: true
                useEPSVwithIPv4: false
                passiveMode: true
        jpa:
            packagesToScanEntityPublic: net.risesoft.y9public.entity
            packagesToScanEntityTenant: net.risesoft.entity
            packagesToScanRepositoryPublic: net.risesoft.y9public.repository
            packagesToScanRepositoryTenant: net.risesoft.repository
        multi-tenant:
            # kafka, db
            event-source: kafka
        log:
            enabled: true
            # kafka, api
            reportMethod: kafka
        session:
            redis:
                enabled: true
                maxInactiveIntervalInSeconds: 3600
        security:
            enabled: true
            cors:
                allowCredentials: true
                allowedOriginPatterns:
                    - https://*.youshengyun.com
                    - http://*.youshengyun.com
                    - http://localhost:7056
                    - http://localhost:8080
                    - http://localhost:8081
                    - http://localhost:7070
                    - http://127.0.0.1:7055
                    - http://127.0.0.1:7056
                    - http://127.0.0.1:17055
            xss:
                ignoreParam:
                    - id
                    - meta
        oauth2:
            resource:
                allowBasicAuthentication: true
                allowFormEncodedBodyParameter: true
                allowUriQueryParameter: true
                #- 单点登录保护的路径,多个路径以英文逗号分隔,如/vue/*,/admin/*
                protectedUrlPatterns: /vue/*
                opaque:
                    #- 客户端唯一标示,由认证服务提供商分配
                    client-id: clientid
                    #- 客户端密钥,由认证服务提供商分配
                    client-secret: secret
                    #- 认证服务器验证访问令牌有效性的路径
                    introspection-uri: http://localhost:7055/sso/oauth2.0/introspect
                    #- 认证服务器获取用户信息路径
                    profile-uri: http://localhost:7055/sso/oauth2.0/profile
